name: example 
on :
  push:
   branches:
   - main

jobs:
 message:
   runs-on: ubuntu-latest
   steps:
     - name: Print message
        run: echo "The secret is ${{ secrets.MY_SECRET }}"

      - name: Use secret as env
        env:
          SECRET_VAR: ${{ secrets.MY_SECRET }}
        run: echo "Secret from env is $SECRET_VAR"
