name: Example
on:
  push:
    branches:
      - main

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "The secret is ${{ secrets.MY_SECRET }}"

      - name: Use secret as env
        env:
          ENV_VAR: rc
        run: echo " env is $ENV_VAR"
